### ISSUE TITLE
AttributeError again

### ISSUE THREAD

**Issue by beloniedamien** [np1/mps-youtube#172]
Hi !

Coming with a new 'AttributeError' :
```
Traceback (most recent call last):                                          
  File "/usr/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.1', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python3.4/site-packages/mps_youtube/main.py", line 4246, in main
    if matchfunction(k, v, userinput):
  File "/usr/lib/python3.4/site-packages/mps_youtube/main.py", line 4149, in matchfunction
    globals()[funcname](*matches)
  File "/usr/lib/python3.4/site-packages/mps_youtube/main.py", line 2950, in play
    play_range(songlist, shuffle, repeat, override)
  File "/usr/lib/python3.4/site-packages/mps_youtube/main.py", line 3042, in play_range
    playsong(song, override=override)
  File "/usr/lib/python3.4/site-packages/mps_youtube/main.py", line 1895, in playsong
    get_streams(song, force=failcount, callback=writestatus)
  File "/usr/lib/python3.4/site-packages/mps_youtube/main.py", line 358, in get_streams
    p = get_pafy(vid, force=force, callback=callback)
  File "/usr/lib/python3.4/site-packages/mps_youtube/main.py", line 327, in get_pafy
    p = pafy.new(item.ytid, callback=callback_fn)
  File "/usr/lib/python3.4/site-packages/pafy/pafy.py", line 138, in new
    return Pafy(url, basic, gdata, signature, size, callback)
  File "/usr/lib/python3.4/site-packages/pafy/pafy.py", line 1046, in __init__
    self.fetch_basic()
  File "/usr/lib/python3.4/site-packages/pafy/pafy.py", line 1091, in fetch_basic
    self.dash = _extract_dash(self._dashurl)
  File "/usr/lib/python3.4/site-packages/pafy/pafy.py", line 279, in _extract_dash
    dashdata = fetch_decode(dashurl)
  File "/usr/lib/python3.4/site-packages/pafy/pafy.py", line 98, in fetch_decode
    encoding = re.search(r"charset=([\w-]+)\s*(:?;|$)", ct).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```
Pafy is already up-to-date. I tried to reinstall mps-youtube, with mplayer and mpv, but nothing works.

Any idea ?

**Comment by np1** [comment]
Feel free to re-open with the requested information when you are ready.
