### ISSUE TITLE
readline.read_history_file(g.READLINE_FILE): PermissionError

### ISSUE THREAD

**Issue by bendem** [np1/mps-youtube#189]
I'm experiencing this error after installing mpsyt (tried with python 2.7 and 3.4).

I tried the solution proposed in #87, but it didn't change anything.

```
$ sudo mpsyt 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/mpsyt", line 7, in <module>
    from mps_youtube import main
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/mps_youtube/__init__.py", line 4, in <module>
    init()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/mps_youtube/main.py", line 854, in init
    init_readline()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/mps_youtube/main.py", line 1027, in init_readline
    readline.read_history_file(g.READLINE_FILE)
PermissionError: [Errno 1] Operation not permitted
```

**Comment by np1** [comment]
Hi, you shouldn't need to run mpsyt using sudo.

I would advise renaming or deleting the `~/.config/mps-youtube` directory and the run mpsyt (without sudo).

**Comment by bendem** [comment]
I only ran it with sudo because it was giving the error without. I can try to remove the config dir and see what happens.

**Comment by bendem** [comment]
Yep, deleting the `~/.config/mps-youtube` folder fixed it, thanks for your work!
