### ISSUE TITLE
PHP exec mpsyt

### ISSUE THREAD

**Issue by arbakker** [np1/mps-youtube#202]
I want to execute mpsyt through PHP `exec()`, but mpsyt fails when executed through `exec()`. mpsyt is configured properly, since the command generated by the script does work when executed in the shell when logged in as my own user. The output from the failing call:
```
Traceback (most recent call last): [2] => File "/usr/local/bin/mpsyt", line 11, in [3] => sys.exit(main.main()) [4] => File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 4246, in main [5] => if matchfunction(k, v, userinput): [6] => File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 4149, in matchfunction [7] => globals()[funcname](*matches) [8] => File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 3695, in play_url [9] => play(override, "1", "_") [10] => File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 2950, in play [11] => play_range(songlist, shuffle, repeat, override) [12] => File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 3028, in play_range [13] => g.content = playback_progress(n, songlist, repeat=False) [14] => File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 1523, in playback_progress [15] => cw = getxy("width") [16] => File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 121, in getxy [17] => max_results = y - 4 if y < 54 else 50 [18] => TypeError: unsupported operand type(s) for -: 'NoneType' and 'int' 
width") [16] => File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 121, in getxy [17] => max_results = y - 4 if y < 54 else 50 [18] => TypeError: unsupported operand type(s) for -: 'NoneType' and 'int' 
```
I cannot tell whether it is a configuration issue or not after searching the internet for while. Hope anyone here can enlighten me?

**Comment by ids1024** [comment]
Try with PR #200.  I think it may fix this issue.

**Comment by arbakker** [comment]
Nice, will let you know whether that fixed the issue.

**Comment by arbakker** [comment]
The fix in https://github.com/np1/mps-youtube/issues/203 solved my problem. I can now use the mpsyt as a headless youtube player, controlled through a webapp. Thanks a bunch!
