### ISSUE TITLE
AssertionError when searching, then when playing - v0.01.47

### ISSUE THREAD

**Issue by Hoolean** [np1/mps-youtube#220]
Version: v0.01.47
Platform: Arch Linux

Howdy hey! Unfortunately, I'm getting an AssertionError when searching:

```Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 921, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 869, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.4/site-packages/mps_youtube/main.py", line 2708, in preload
    stream = get_streams(song)
  File "/usr/lib/python3.4/site-packages/mps_youtube/main.py", line 338, in get_streams
    p = get_pafy(vid, force=force, callback=callback)
  File "/usr/lib/python3.4/site-packages/mps_youtube/main.py", line 307, in get_pafy
    p = pafy.new(item.ytid, callback=callback_fn)
  File "/usr/lib/python3.4/site-packages/pafy/pafy.py", line 137, in new
    return Pafy(url, basic, gdata, signature, size, callback)
  File "/usr/lib/python3.4/site-packages/pafy/pafy.py", line 1007, in __init__
    self.fetch_basic()
  File "/usr/lib/python3.4/site-packages/pafy/pafy.py", line 1024, in fetch_basic
    assert self.ciphertag is ('s' in self.sm[0])
AssertionError```

and then another one when attempting to play a track, after receiving the first error, this time near-immediately fatal:

```Traceback (most recent call last):                                          
  File "/usr/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.01.47', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python3.4/site-packages/mps_youtube/main.py", line 4133, in main
    if matchfunction(k, v, userinput):
  File "/usr/lib/python3.4/site-packages/mps_youtube/main.py", line 4037, in matchfunction
    globals()[funcname](*matches)
  File "/usr/lib/python3.4/site-packages/mps_youtube/main.py", line 2661, in play
    play_range(songlist, shuffle, repeat, override)
  File "/usr/lib/python3.4/site-packages/mps_youtube/main.py", line 2753, in play_range
    playsong(song, override=override)
  File "/usr/lib/python3.4/site-packages/mps_youtube/main.py", line 1698, in playsong
    get_streams(song, force=failcount, callback=writestatus)
  File "/usr/lib/python3.4/site-packages/mps_youtube/main.py", line 338, in get_streams
    p = get_pafy(vid, force=force, callback=callback)
  File "/usr/lib/python3.4/site-packages/mps_youtube/main.py", line 307, in get_pafy
    p = pafy.new(item.ytid, callback=callback_fn)
  File "/usr/lib/python3.4/site-packages/pafy/pafy.py", line 137, in new
    return Pafy(url, basic, gdata, signature, size, callback)
  File "/usr/lib/python3.4/site-packages/pafy/pafy.py", line 1007, in __init__
    self.fetch_basic()
  File "/usr/lib/python3.4/site-packages/pafy/pafy.py", line 1024, in fetch_basic
    assert self.ciphertag is ('s' in self.sm[0])
AssertionError```

I hope I'm not doing anything silly. Any ideas what the issue may be?

**Comment by Hoolean** [comment]
Stupidity confirmed - I'm using a prehistoric version. I've updated and now everything works fine and dandy ^_^
