### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by robotrono** [np1/mps-youtube#237]
when playing a video with japanese letters I get this error:

```
Num  Title                                                               Time
 1   ?Chill House?Diviners ft. Contacreast - Tropic Love              05:00
 2   ?Chill?Oh Wonder - Technicolour Beat (Urban Contact Remix)       03:33
 3   K?lsch - LORELEY                                                   06:46
 4   Amateras Records -Tear Rain (cYsmix feat Emmy)                     04:05
 5   ?Chill?W I S H I W A S ft. Cameron Walker - Cutting Ties         05:01
 6   Rolling Girls OP                                                   01:30
 7   Kero Kero Bonito - Flamingo                                        03:18
 8   50 Cent - Pilot                                                    03:08
 9   Biggie Smalls - Party & Bullshit                                   03:42
10   Nas - Mastermind (Sourface Remix)                                  03:56
11   Kendrick Lamar - Blow My High                                      03:35
12   Frank Ocean - Thinkin Bout You (Ryan Hemsworth Bootleg)            03:59
13   Golden Boy - That Thing                                            06:43
14   Clubfeet - Cape Town (Panama Remix)                                05:09
15   Reva DeVito - Friday Night (Prod. By KAYTRANADA)                   04:28
16   Tinashe - Vulnerable (Pomo Remix)                                  04:28
17   Jaymes Young - Habits Of My Heart (Sufjan Stevens Remake)          03:35
18   Tom Misch & Carmody - Atmosphere                                   04:22
19   HAIM - Don't Save Me (Cyril Hahn Remix)                            05:17
20   Real Connoisseur - Nobodys Fool (I'll Be Good To You)              07:53
21   Naughty Boy - La La La (Ft. Sam Smith) (DEVolution Remix)          05:46

    [<-] seek [->]       [9] volume [0]
    [DN] SEEK [UP]       [space] pause       [q] return

    ?Chill House?Diviners ft. Contacreast - Tropic Love [05:00]
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 2029, in launch_player stderr=subprocess.STDOUT, bufsize=1)
  File "/usr/lib/python3.4/subprocess.py", line 858, in __init__ restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1394, in _execute_child restore_signals, start_new_session, preexec_fn)
UnicodeEncodeError: 'ascii' codec can't encode character '\u3010' in position 0: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 11, in <module> sys.exit(main.main())
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 4421, in main
    if matchfunction(k, v, userinput):
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 4324, in matchfunction
    func(*matches)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 3122, in play
    play_range(songlist, shuffle, repeat, override)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 3214, in play_range
    returncode = playsong(song, override=override)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 1955, in playsong
    returncode = launch_player(song, songdata, cmd)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 2068, in launch_player
    if p and p.poll() is None: UnboundLocalError: local variable 'p' referenced before assignmen
```

VPS, Ubuntu 12.04, Python 3.4

**Comment by ids1024** [comment]
I think this should be fixed now in the develop branch. You can install that by running `pip install --upgrade https://github.com/np1/mps-youtube/archive/develop.zip`.

**Comment by spvkgn** [comment]
I have the same error with 0.2.4 and python 2.7.3 when I do query in specified user uploads. While as query with no specified user does work.
```
~ $ mpsyt --debug user rtrussian/США

mpsyt version  : 0.2.4 
   notes       : released 13 May 2015
pafy version   : 0.3.72
Python version : 2.7.3 (default, Dec 18 2014, 19:03:52) 
[GCC 4.6.3]
Processor      : i686
Machine type   : i686
Architecture   : 32bit, ELF
Platform       : Linux-3.2.0-79-generic-pae-i686-with-LinuxMint-13-maya
sys.stdout.enc : UTF-8
default enc    : ascii
Config dir     : /home/pavel/.config/mps-youtube
env:TERM       : screen-256color
env:SHELL      : /bin/bash
env:LANG       : ru_RU.UTF-8
--




Enter /search-term to search or [h]elp
Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.4', 'console_scripts', 'mpsyt')()
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 4752, in main
    if matchfunction(k, v, userinput):
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 4648, in matchfunction
    func(*matches)
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 2544, in usersearch
    usersearch_id('/'.join([user, channel_id, term]), page, splash)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)
```

**Comment by spvkgn** [comment]
With `pip install --upgrade https://github.com/np1/mps-youtube/archive/develop.zip` I get 
```
~ $ mpsyt --debug
Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.4', 'console_scripts', 'mpsyt')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 552, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2672, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2345, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2351, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/__init__.py", line 1, in <module>
    from .main import init
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 56, in <module>
    from urllib.request import urlopen, build_opener
ImportError: No module named request
```

**Comment by hrnr** [comment]
development branch has moved to python 3. Use python3/pip3 and you will be fine.
