### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by robotrono** [np1/mps-youtube#240]
Now I get this error on Ubuntu 14.04 when play a jp video.
VPS Ubuntu 14.04 x64 Python 2.7

```
Num  Title                                                               Time
 1   ?Chill House?Diviners ft. Contacreast - Tropic Love              05:00
 2   ?Chill?Oh Wonder - Technicolour Beat (Urban Contact Remix)       03:33
 3   K?lsch - LORELEY                                                   06:46
 4   Amateras Records -Tear Rain (cYsmix feat Emmy)                     04:05
 5   ?Chill?W I S H I W A S ft. Cameron Walker - Cutting Ties         05:01
 6   Rolling Girls OP                                                   01:30
 7   Kero Kero Bonito - Flamingo                                        03:18
 8   50 Cent - Pilot                                                    03:08
 9   Biggie Smalls - Party & Bullshit                                   03:42
10   Nas - Mastermind (Sourface Remix)                                  03:56
11   Kendrick Lamar - Blow My High                                      03:35
12   Frank Ocean - Thinkin Bout You (Ryan Hemsworth Bootleg)            03:59
13   Golden Boy - That Thing                                            06:43
14   Clubfeet - Cape Town (Panama Remix)                                05:09
15   Reva DeVito - Friday Night (Prod. By KAYTRANADA)                   04:28
16   Tinashe - Vulnerable (Pomo Remix)                                  04:28
17   Jaymes Young - Habits Of My Heart (Sufjan Stevens Remake)          03:35
18   Tom Misch & Carmody - Atmosphere                                   04:22
19   HAIM - Don't Save Me (Cyril Hahn Remix)                            05:17
20   Real Connoisseur - Nobodys Fool (I'll Be Good To You)              07:53
21   Naughty Boy - La La La (Ft. Sam Smith) (DEVolution Remix)          05:46

    [<-] seek [->]       [9] volume [0]
    [DN] SEEK [UP]       [space] pause       [q] return

    ?Chill House?Diviners ft. Contacreast - Tropic Love [05:00]
Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 11, in <module>
    sys.exit(main.main())
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 4421, in main
    if matchfunction(k, v, userinput):
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 4324, in matchfunction
    func(*matches)
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 3122, in play
    play_range(songlist, shuffle, repeat, override)
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 3214, in play_range
    returncode = playsong(song, override=override)
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 1955, in playsong
    returncode = launch_player(song, songdata, cmd)
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 2068, in launch_player
    if p and p.poll() is None:
UnboundLocalError: local variable 'p' referenced before assignment
```

**Comment by bendem** [comment]
duplicate of #237
