### ISSUE TITLE
mplayer works for playback, mpv makes mps-youtube crash

### ISSUE THREAD

**Issue by GijsTimmers** [np1/mps-youtube#243]
```
[me@pc ~]$ mplayer -version
Unknown option on the command line: --version
Error parsing option on the command line: -version
MPlayer2 2.0-701-gd4c5b7f-2ubuntu2 (C) 2000-2012 MPlayer Team
[me@pc ~]$ mpv --version
mpv git-a18dc01 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on 2015-04-06T01:03:48
ffmpeg library versions:
   libavutil       54.20.100
   libavcodec      56.26.100
   libavformat     56.25.101
   libswscale      3.1.101
   libavfilter     5.11.102
   libswresample   1.1.100
```
Trying to play the `youtube-dl` test video makes `mps-youtube` crash:

```
Num  Title                                                               Time
 1   youtube-dl test video "'/\ä↭𝕐                                      00:10
 2   HOW TO PASS YOUR DRIVERS LICENSE TEST                              12:12
 3   2015 California DMV written tests - 5 different tests              42:52
 4   Volvo 240 DL Car Video Review 240GL 240DL Test Drive Videos        10:36
 5   Fast & Furious Nerd Shocks Instructors                             04:08
 6   Driver Education info from Drive Smart Driving School: How to pas  13:06
 7   Youtube-dl Annotation Test                                         00:11
 8   DMV & Driving Test Tips by Rock O. Kendall (Full version of Road   32:12
 9   Driver's Test Prank!                                               07:27
10   Mansfield, Ohio driver's license test/exam.                        11:42
11   Victoria Beckham - Hilarious video - Drivers license test          01:06
12   Adam Savage's One Day Builds: Han Solo's DL-44 Blaster             16:37
13   Free Drivers Education Video - How to prepare and pass the writte  07:54
14   UK Driving Test 1/6 - LDC driving schools                          10:01
15   How To Pass Your Drivers License Test (Driving Footage)            05:31
16   Practice: How to pass the NZ full licence test                     04:31
17   Jeff Gordon: Test Drive 2 | Pepsi Max                              04:51
18   Texas Driver Permit Test - Traffic Signals - Practice Exam # 1 -P  13:56
19   Chevy salesman prank with Jeff Gordon                              03:57
20   Car and Driver: Tested : 2013 Tesla Model S - Review - CAR and DR  16:16

    [←] seek [→]       [9] volume [0]
    [↓] SEEK [↑]       [space] pause       [q] return    

    youtube-dl test video "'/\ä↭𝕐 [00:10]
Traceback (most recent call last):                                          
  File "/usr/local/bin/mpsyt", line 11, in <module>
    sys.exit(main.main())
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 4421, in main
    if matchfunction(k, v, userinput):
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 4324, in matchfunction
    func(*matches)
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 3122, in play
    play_range(songlist, shuffle, repeat, override)
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 3214, in play_range
    returncode = playsong(song, override=override)
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 1955, in playsong
    returncode = launch_player(song, songdata, cmd)
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 2066, in launch_player
    os.unlink(sockpath)
OSError: [Errno 2] Bestand of map bestaat niet: '/tmp/mpsyt-mpv_Rs6lt.sock'
```

**Comment by ids1024** [comment]
Does PR #236 help? It should eliminate that specific error, though I suspect something else is wrong.

**Comment by GijsTimmers** [comment]
Hi, I've just cloned your fork, and tried to run the `v0.2.4-dev` version. I still can't get mpv to work, but the error looks different. I've uploaded a screenrecord [here](https://vid.me/HwxB).

**Comment by ids1024** [comment]
Run this command in mpsyt:

    set playerargs --msg-level=all=status

Then try to play the video again. That should provide useful debug information.

**Comment by GijsTimmers** [comment]
I have no idea what happened, but playback with `mpv` magically started working today. May have something to do with some `apt-get` updates I ran yesterday.

Thank you for your support. I will close this issue now, until this problem re-appears.
