### ISSUE TITLE
Exception while running mpsyt

### ISSUE THREAD

**Issue by areszm** [np1/mps-youtube#279]
$ mpsyt 
Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.4', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 521, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2632, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2312, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2318, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/mps_youtube/__init__.py", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube-0.2.4-py2.7.egg/mps_youtube/main.py", line 138
    print(xenc(stuff), end=end)
                          ^
SyntaxError: invalid syntax

**Comment by ids1024** [comment]
What version of mpsyt? If is's the develop branch, you need python 3.

**Comment by kkrolczyk** [comment]
I had similar error:

$  mpsyt
Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2708, in <module>
    working_set.require(\__requires\__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pafy>=0.3.74

while on Ubuntu 12.04 with both Python2 and Python 3.2 installed.
$  pip3 freeze
(...)
mps-youtube==0.2.5
pafy==0.3.74
(...)

And files were present in /usr/local/lib/python3.2/dist-packages/{pafy-0.3.74.dist-info, pafy}
(which is kind of different, since all other modules there - have name syntax like NAME-VER-egg-info)

but anyway - problem was solved by:

$  sudo easy_install3 pafy
