### ISSUE TITLE
can't change pages in playlists

### ISSUE THREAD

**Issue by HptmHavoc** [np1/mps-youtube#287]
Hi,

i can't change pages in a playlist. I get following error;

Traceback (most recent call last):
  File "/usr/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.4', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python3.4/site-packages/mps_youtube-0.2.4-py3.4.egg/mps_youtube/main.py", line 4843, in
main
  File "/usr/lib/python3.4/site-packages/mps_youtube-0.2.4-py3.4.egg/mps_youtube/main.py", line 4743, in
matchfunction
  File "/usr/lib/python3.4/site-packages/mps_youtube-0.2.4-py3.4.egg/mps_youtube/main.py", line 4128, in
nextprev
  File "/usr/lib/python3.4/site-packages/mps_youtube-0.2.4-py3.4.egg/mps_youtube/main.py", line 4352, in
plist
TypeError: unsupported operand type(s) for -: 'str' and 'int'

Tested with mps-youtube-git from aur and dev branch.

**Comment by ids1024** [comment]
Known issue; should be fixed soon.

**Comment by ids1024** [comment]
Should be fixed in the git version or the next release. To install the git version, run `pip install --upgrade https://github.com/np1/pafy/archive/develop.zip https://github.com/np1/mps-youtube/archive/develop.zip`.
