### ISSUE TITLE
Dev version  can't play any videos for me

### ISSUE THREAD

**Issue by Atlantic777** [np1/mps-youtube#299]
Hi!

From discussion on issue #298 I learned that dev version actually should work.

I installed it like this:

`sudo pip3  install --upgrade https://github.com/np1/pafy/archive/develop.zip https://github.com/np1/mps-youtube/archive/develop.zip`

When I try to play some video it crashes with this traceback.

What can be wrong?

```
Traceback (most recent call last):                                                                              
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 2101, in playsong
    get_streams(song, force=failcount, callback=writestatus)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 345, in get_streams
    p = get_pafy(vid, force=force, callback=callback)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 314, in get_pafy
    p = pafy.new(item.ytid, callback=callback_fn)
  File "/usr/local/lib/python3.4/dist-packages/pafy/pafy.py", line 137, in new
    return Pafy(url, basic, gdata, signature, size, callback)
  File "/usr/local/lib/python3.4/dist-packages/pafy/pafy.py", line 1068, in __init__
    self.fetch_basic()
  File "/usr/local/lib/python3.4/dist-packages/pafy/pafy.py", line 1111, in fetch_basic
    self.dash = _extract_dash(self._dashurl)
  File "/usr/local/lib/python3.4/dist-packages/pafy/pafy.py", line 294, in _extract_dash
    dashdata = fetch_decode(dashurl)
  File "/usr/local/lib/python3.4/dist-packages/pafy/pafy.py", line 90, in fetch_decode
    req = g.opener.open(url)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 2101, in playsong
    get_streams(song, force=failcount, callback=writestatus)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 345, in get_streams
    p = get_pafy(vid, force=force, callback=callback)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 314, in get_pafy
    p = pafy.new(item.ytid, callback=callback_fn)
  File "/usr/local/lib/python3.4/dist-packages/pafy/pafy.py", line 137, in new
    return Pafy(url, basic, gdata, signature, size, callback)
  File "/usr/local/lib/python3.4/dist-packages/pafy/pafy.py", line 1068, in __init__
    self.fetch_basic()
  File "/usr/local/lib/python3.4/dist-packages/pafy/pafy.py", line 1111, in fetch_basic
    self.dash = _extract_dash(self._dashurl)
  File "/usr/local/lib/python3.4/dist-packages/pafy/pafy.py", line 294, in _extract_dash
    dashdata = fetch_decode(dashurl)
  File "/usr/local/lib/python3.4/dist-packages/pafy/pafy.py", line 90, in fetch_decode
    req = g.opener.open(url)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 2101, in playsong
    get_streams(song, force=failcount, callback=writestatus)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 345, in get_streams
    p = get_pafy(vid, force=force, callback=callback)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 314, in get_pafy
    p = pafy.new(item.ytid, callback=callback_fn)
  File "/usr/local/lib/python3.4/dist-packages/pafy/pafy.py", line 137, in new
    return Pafy(url, basic, gdata, signature, size, callback)
  File "/usr/local/lib/python3.4/dist-packages/pafy/pafy.py", line 1068, in __init__
    self.fetch_basic()
  File "/usr/local/lib/python3.4/dist-packages/pafy/pafy.py", line 1111, in fetch_basic
    self.dash = _extract_dash(self._dashurl)
  File "/usr/local/lib/python3.4/dist-packages/pafy/pafy.py", line 294, in _extract_dash
    dashdata = fetch_decode(dashurl)
  File "/usr/local/lib/python3.4/dist-packages/pafy/pafy.py", line 90, in fetch_decode
    req = g.opener.open(url)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.4', 'console_scripts', 'mpsyt')()
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 4771, in main
    if matchfunction(k, v, userinput):
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 4671, in matchfunction
    func(*matches)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 3441, in play
    play_range(songlist, shuffle, repeat, override)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 3534, in play_range
    returncode = playsong(song, override=override)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 2113, in playsong
    return playsong(song, failcount=failcount, override=override)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 2113, in playsong
    return playsong(song, failcount=failcount, override=override)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 2113, in playsong
    return playsong(song, failcount=failcount, override=override)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 2125, in playsong
    cmd, songdata = generate_real_playerargs(song, override, failcount)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 2015, in generate_real_playerargs
    size = get_size(song.ytid, stream['url'])
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 418, in get_size
    stream['size'] = get_content_length(url, preloading=preloading)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 250, in get_content_length
    response = urlopen(url).decode()
AttributeError: 'HTTPResponse' object has no attribute 'decode'
```

**Comment by ids1024** [comment]
I just pushed 858a365a4c5a5d71df0427e97e83ec2afdc2f904, which fixes at least one of the issues. Can you try again?

**Comment by Atlantic777** [comment]
Yay, it works! It was so simple, I should have tried it and send a pull request. -.-

Thanks @ids1024, I'm can now switch to dev.
