### ISSUE TITLE
error upon latest pip upgrade of mps-youtube

### ISSUE THREAD

**Issue by w-hive** [np1/mps-youtube#304]
Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.5', 'console_scripts', 'mpsyt')()
  File "build/bdist.macosx-10.7-x86_64/egg/pkg_resources/__init__.py", line 552, in load_entry_point
  File "build/bdist.macosx-10.7-x86_64/egg/pkg_resources/__init__.py", line 2672, in load_entry_point
  File "build/bdist.macosx-10.7-x86_64/egg/pkg_resources/__init__.py", line 2345, in load
  File "build/bdist.macosx-10.7-x86_64/egg/pkg_resources/__init__.py", line 2351, in resolve
  File "/usr/local/lib/python2.7/site-packages/mps_youtube/__init__.py", line 1, in <module>
    from .main import init
  File "/usr/local/lib/python2.7/site-packages/mps_youtube/main.py", line 54, in <module>
    from urllib.request import urlopen, build_opener
ImportError: No module named request

System is Mac OS X 10.7.5

**Comment by lol768** [comment]
I believe there is no support for Python 2. You might want to use the pip3 command or similar.

**Comment by w-hive** [comment]
Ha, indeed. Fixed, cheers. :)
